config/routes.rb
Rails.application.routes.draw do
  # Rails Admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Blazer
  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "queries"
  end

  # Devise
  devise_for :users, controllers: {registrations: 'users/registrations'}
  devise_scope :user do
      delete 'users/delete_avatar', to: "users/registrations#delete_avatar"
  end

  # Generale Routes
  root to: 'pages#home'
  get '/faq', to:'pages#faq'

  # Contacts
  resources :contacts, only: [:new, :create]

  # Ranking Histories
  resources :ranking_histories, only: [:index, :edit, :update], path: 'ranking-histories' do
    post '/validate',  to:'ranking_histories#validate'
  end

  # Players
  resources :players, only: [:new, :create, :edit, :update] do
    post '/validate', to:'players#validate'
  end

  get '/players', to:'players#index', constraints: lambda { |req| req.format == :json }
  get '/players/:id', to:'players#show', constraints: lambda { |req| req.format == :json }
  get '/players-validations', to:'players#validations'
  get '/stats', to:'players#stats'
  get '/compare', to:'players#compare'

  # Tournaments
  resources :tournaments, only: [:new, :create, :edit, :update] do
    post '/validate', to:'tournaments#validate'
  end

  get '/tournaments', to:'tournaments#index', constraints: lambda { |req| req.format == :json }
  get '/tournaments-validations', to:'tournaments#validations'

  # Games
  resources :games, except: [:show] do
    post '/validate',  to:'games#validate'
  end

end

app/models/category.rb
class Category < ApplicationRecord
    # Relations
    has_many :tournaments
    has_many :category_rankings
    has_many :rankings, through: :category_rankings
    has_many :category_rounds
end

app/models/category_ranking.rb
class CategoryRanking < ApplicationRecord
    # Relations
    belongs_to :category
    belongs_to :ranking
end

app/models/category_round.rb
class CategoryRound < ApplicationRecord
    # Relations
    belongs_to :category
    belongs_to :round
end

app/models/club.rb
class Club < ApplicationRecord
    # Relations
    has_many :courts
    has_many :tournaments
    has_many :players
end

app/models/contact_message.rb
class ContactMessage
  include ActiveModel::Model
  attr_accessor :name, :email, :subject, :body
  validates :name, :email, :subject, :body, presence: true
end

app/models/court.rb
class Court < ApplicationRecord
  # Relations
  belongs_to :club
  belongs_to :court_type
end

app/models/court_type.rb
class CourtType < ApplicationRecord
    # Relations
    has_many :courts
    has_many :games
end

app/models/division.rb
class Division < ApplicationRecord
  # Relations
  has_many :division_rankings
  has_many :interclubs
end
    

app/models/division_ranking.rb
class DivisionRanking < ApplicationRecord
  # Relations
  belongs_to :division
  belongs_to :ranking
end

app/models/game.rb
class Game < ApplicationRecord
  # Relations
  belongs_to :interclub, optional: true
  belongs_to :tournament, optional: true
  belongs_to :court_type, optional: true
  belongs_to :player, optional: true
  belongs_to :round, optional: true
  has_many :game_players, dependent: :destroy
  has_many :players, through: :game_players

  # Nested attributes
  has_many :game_sets, dependent: :destroy
  accepts_nested_attributes_for :game_sets, allow_destroy: true
  
end

app/models/game_player.rb
class GamePlayer < ApplicationRecord
  # Relations
  belongs_to :player
  belongs_to :game
  belongs_to :ranking, optional: true

  # Validations
  validates :player, :game, presence: true
  validates :victory, :validated, inclusion: { in: [ '0', '1', true, false ] }

end

app/models/game_set.rb
class GameSet < ApplicationRecord
  # Relations
  belongs_to :game
  
  # Nested Attributes
  has_one :tie_break, dependent: :destroy
  accepts_nested_attributes_for :tie_break, allow_destroy: true

  # Validations
  validates :game, :set_number, :games_1, :games_2, presence: true
end

app/models/interclub.rb
class Interclub < ApplicationRecord
  # Relations
  belongs_to :division
  has_many :games
end
  

app/models/player.rb
class Player < ApplicationRecord
  # Relations
  belongs_to :user, optional: true
  belongs_to :club
  has_many :game_players
  has_many :games, through: :game_players
  has_many :tournaments, through: :games
  has_many :categories, through: :tournaments
  has_many :ranking_histories, dependent: :destroy
  has_many :ranking, through: :ranking_histories

  # Reflexive Relation
  belongs_to :player_creator, class_name: 'Player', optional: true, foreign_key: 'player_creator_id'
  has_many :players_created, class_name: 'Player', foreign_key: 'player_creator_id'

  # Nested attributes
  accepts_nested_attributes_for :ranking_histories

  # Validations
  validates :affiliation_number, :gender, :first_name, :last_name, :dominant_hand, presence: true
  validates :birthdate, presence: true, unless: :user_added?
  validates :affiliation_number, format: { with: /\A\d{7}\z/, message: "le numéro d'affiliation doit être composé de 7 chiffres"}, allow_blank: true
  validate :affiliation_number_check, on: :create
  
  # PG Search
  include PgSearch::Model
  pg_search_scope :search_by_name_and_affiliation_number,
    against: [:first_name, :last_name, :affiliation_number],
    using: {
      tsearch: { prefix: true }
  }
  
  private 

  # Custom Validations
  def affiliation_number_check
    player = Player.find_by_affiliation_number(self.affiliation_number)
    # Created through nested attributes
    if self.user
      if player
          errors.add(:affiliation_number, 'Déjà associé à un autre e-mail') if (!player.user_id.nil? && (player.user.email != self.user.email))
      end
    # Create as a stand-alone player
    else
      errors.add(:affiliation_number, 'Déjà existant') if (player && self.new_record?)
    end
  end
  
  def user_added?
    !self.player_creator_id.nil?
  end

end

app/models/ranking.rb
class Ranking < ApplicationRecord
    # Relations
    has_many :ranking_histories
    has_many :category_rankings
end

app/models/ranking_history.rb
class RankingHistory < ApplicationRecord
  # Relations
  belongs_to :ranking
  belongs_to :player

  # Validations
  validates :player, :year, :year_number, presence: true
  validates :player_id, uniqueness: { scope: [:year, :year_number] }

end

app/models/round.rb
class Round < ApplicationRecord
    # Relations
    has_many :category_rounds
    has_many :games
end

app/models/tie_break.rb
class TieBreak < ApplicationRecord
  # Relations
  belongs_to :game_set

  # Validations
  validates :game_set, :points_1, :points_2, presence: true
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  # Relations
  belongs_to :club
  belongs_to :category
  belongs_to :player, optional: true
  has_many :games
  
  # Validations
  validates :start_date, :end_date, presence: true
  validates :club, uniqueness: { scope: [:category, :start_date, :end_date] }
  validates :nbr_participants, numericality: { only_integer: true }
  validate :valid_date

  private

  def valid_date
    unless self.start_date.blank? || self.end_date.blank?
      errors.add(:end_date, 'doit être postérieure à la date de début') unless self.end_date > self.start_date
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Concerns
  include NestedUserConcern
  
  # Devise
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  # Active Storage
  has_one_attached :avatar

  # Validations
  validates :terms_of_service, acceptance: true, on: :create
  
  # Relations
  has_one :player
  
  # Nested Attributes
  accepts_nested_attributes_for :player

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>"> 

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div id='banner'>
    <div>
        <h1 id='banner-cta'>Enregistre, analyse et compare <br> tes résultats de tennis en un instant</h1>
        <a href='<%= new_user_registration_path %>' id='banner-button'>Inscris-toi</a>
    </div>
</div>

<div class='container'>
    <div class='explainer display-flex space-between'>
        <div class='explainer-text display-flex align-center'>
            <div>
                <p> <em> Sauvegarde </em> tes résultats sans risque de les perdre. </p>
                <p> Nous garantissons la continuité des données à vie. </p>
                <p> Tu pourras ainsi suivre ton évolution au fil des ans  </p>
            </div>
        </div>
        <div class='explainer-img-block'>
            <%= image_tag('landing/save.png', class: 'explainer-img') %>
        </div>
    </div>

     <div class='explainer display-flex space-between'>
        <div class='explainer-img-block'>
            <%= image_tag('landing/stats.png', class: 'explainer-img') %>
        </div>
        <div class='explainer-text display-flex align-center'>
            <div>
                <p> <em> Analyse </em> tes résultats avec toute une série de statistiques mises à disposition. </p>
                <p> Ratio de victoire/défaites par type de surface, classement, tie-breaks gagnés, etc </p>
            </div>
        </div>
    </div>

    <div class='explainer display-flex space-between'>
        <div class='explainer-text display-flex align-center'>
            <div>
                <p> <em> Compare </em> tes résultats avec tes amis ou n'importe quel autre joueur(euse). </p>
                <p> Cela te permettra en quelques clics de te situer vis-à-vis d'autres joueurs(euses). </p>
            </div>
        </div>
        <div class='explainer-img-block'>
          <%= image_tag('landing/compare.png', class: 'explainer-img') %>
        </div>
    </div>

</div>

app/views/shared/_dropdown.html.erb
<div data-controller='dropdown' class='dropdown'>
  <%= button %>
  <div data-target='dropdown.popup' class='dropdown-content'>
    <% content.each do |element| %>
      <%= element %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class='alert alert-info alert-dismissible fade show m-1' role='alert'>
    <%= notice %>
    <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
      <span aria-hidden='true'>&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class='alert alert-warning alert-dismissible fade show m-1' role='alert'>
    <%= alert %>
    <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
      <span aria-hidden='true'>&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class='navbar-tennis'>
  <% if current_user %>
    <%= link_to image_tag('navbar/teqis.png', class: 'navbar-logo'), games_path %>
  <% else %>
    <%= link_to image_tag('navbar/teqis.png', class: 'navbar-logo'), root_path %>
  <% end %>
  <div class='navbar-right-section'>
    <% if current_user %>
      <div class='navbar-collapsable'>
        <% if current_user.admin %>
          <%= link_to('Admin', rails_admin_path, class: 'navbar-link')%>
          <%= link_to('Blazer', blazer_path, class: 'navbar-link')%>
          <div data-controller='dropdown' class='dropdown'>
            <div class='navbar-link' data-target='dropdown.button' data-action='click->dropdown#toggleVisibility' role='button' aria-haspopup='true' aria-expanded='false'> Validation </div>  
            <div data-target='dropdown.popup' class='dropdown-content'>
              <%= link_to('Joueur', players_validations_path, class: 'dropdown-link')%>
              <%= link_to('Tournoi', tournaments_validations_path, class: 'dropdown-link')%>
            </div>
          </div>
        <% end %>
        <div data-controller='dropdown' class='dropdown'>
          <div class='navbar-link' data-target='dropdown.button' data-action='click->dropdown#toggleVisibility' role='button' aria-haspopup='true' aria-expanded='false'> Encodage </div>  
          <div data-target='dropdown.popup' class='dropdown-content'>
            <%= link_to('Match', new_game_path, class: 'dropdown-link')%>
            <% if current_user.admin %>
              <%= link_to('Tournoi', new_tournament_path, class: 'dropdown-link')%>
            <% end %>
            <%= link_to('Joueur', new_player_path, class: 'dropdown-link')%>
          </div>
        </div>
        <%= link_to('Résultats', games_path, class: 'navbar-link') %>
        <%= link_to('Stats', stats_path, class: 'navbar-link') %>
        <%= link_to('Compare', compare_path, class: 'navbar-link') %>
        <%= link_to('Classement', ranking_histories_path, class: 'navbar-link') %>
      </div>
      <% if current_user.admin %>
        <div data-controller='dropdown' class='dropdown'>
          <%= image_tag 'navbar/check.png', class: 'navbar-check', 
                                                     data: { target:'dropdown.button', action: 'click->dropdown#toggleVisibility'}, 
                                                     role:'button', 
                                                     'aria-haspopup': 'true', 
                                                     'aria-expanded': 'false' %>
          <div data-target='dropdown.popup' class='dropdown-content'>
            <%= link_to('Joueur', players_validations_path, class: 'dropdown-link')%>
            <%= link_to('Tournoi', tournaments_validations_path, class: 'dropdown-link')%>
            <%= link_to('Admin', rails_admin_path, class: 'dropdown-link')%>
            <%= link_to('Blazer', blazer_path, class: 'dropdown-link')%>
          </div>
        </div>
      <% end %>
      <div data-controller='dropdown' class='dropdown'>
        <%= image_tag 'navbar/add.png', class: 'navbar-plus', 
                                                     data: { target:'dropdown.button', action: 'click->dropdown#toggleVisibility'}, 
                                                     role:'button', 
                                                     'aria-haspopup': 'true', 
                                                     'aria-expanded': 'false' %>
        <div data-target='dropdown.popup' class='dropdown-content'>
          <%= link_to('Match', new_game_path, class: 'dropdown-link')%>
          <% if current_user.admin %>
            <%= link_to('Tournoi', new_tournament_path, class: 'dropdown-link')%>
          <% end %>
          <%= link_to('Joueur', new_player_path, class: 'dropdown-link')%>
        </div>
      </div>
      <div data-controller='dropdown' class='dropdown'>
        <%= image_tag 'navbar/menu.png', class: 'navbar-sandwich', 
                                                     data: { target:'dropdown.button', action: 'click->dropdown#toggleVisibility'}, 
                                                     role:'button', 
                                                     'aria-haspopup': 'true', 
                                                     'aria-expanded': 'false' %>
        <div data-target='dropdown.popup' class='dropdown-content'>
          <%= link_to('Résultats', games_path, class: 'navbar-link') %>
          <%= link_to('Stats', stats_path, class: 'navbar-link') %>
          <%= link_to('Compare', compare_path, class: 'navbar-link') %>
          <%= link_to('Classement', ranking_histories_path, class: 'navbar-link') %>
        </div>
      </div>
      <h6 class='navbar-points'> <%= current_user.player.ranking_histories.max_by{|ranking| ranking.start_date}.points %> pts</h6>
      <div data-controller='dropdown' class='dropdown'>
        <% if current_user.avatar.attached? %>
          <%= cl_image_tag current_user.avatar.key, class: 'avatar', 
                                                    data: {target:'dropdown.button', action: 'click->dropdown#toggleVisibility'}, 
                                                    role: 'button', 
                                                    'aria-haspopup': 'true', 
                                                    'aria-expanded': 'false'  %>
        <% else %>
          <%= image_tag 'navbar/tennis_ball.svg', class: 'avatar', 
                                                            data: {target:'dropdown.button', action: 'click->dropdown#toggleVisibility'}, 
                                                            role:'button', 
                                                            'aria-haspopup': 'true', 
                                                            'aria-expanded': 'false'  %>
        <% end %>
        <div data-target='dropdown.popup' class='dropdown-content'>
          <%= link_to('Mon compte', edit_user_registration_path , class: 'dropdown-link') %>
          <%= link_to('FAQ', faq_path , class: 'dropdown-link') %>
          <%= link_to('Contact', new_contact_path , class: 'dropdown-link') %>
          <%= link_to('Déconnexion', destroy_user_session_path, method: :delete, class: 'dropdown-link') %>
        </div>
      </div>
    <% else %>
      <%= link_to('FAQ', faq_path , class: 'navbar-link') %>
      <%= link_to('Contact', new_contact_path , class: 'navbar-link') %>
      <%= link_to('Connexion', new_user_session_path , class: 'navbar-link') %>
      <%= link_to("S'inscrire", new_user_registration_path , class: 'navbar-link') %>
    <% end  %>
  </div>
</div>

app/views/shared/_year_and_player_search.html.erb
<div class='display-flex space-between'>
    <div>
      <div class='display-flex'>
        <div class='autocomplete' data-target='autocomplete.wrapper'>
            <input class='player-search' placeholder='Cherche un joueur' autocomplete='off' data-target='filter.playerInput autocomplete.autocomplete' data-action='input->autocomplete#autocomplete' data-gender="" type='text'>
        </div>
        <div class='search-btn' data-action=<%= (search_type == 'compare' ? 'click->filter#selectComparisons' : (search_type == 'games' ? 'click->filter#selectGames' : 'click->filter#selectStats')) %>>
          <i class='fas fa-search search-icon'></i>
        </div>
      </div>
    </div>
    <%= select_year(max_date, {start_year: max_date, end_year: min_date, include_blank: true}, 
                              {class: 'select-year', data: {target: 'filter.year', action: (search_type == 'compare' ? 'filter#selectComparisons' : (search_type == 'games' ? 'filter#selectGames' : 'filter#selectStats'))}})%>
</div>