config/routes.rb
Rails.application.routes.draw do
  # Rails Admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Blazer
  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "queries"
  end

  # Devise
  devise_for :users, controllers: {registrations: 'users/registrations'}
  devise_scope :user do
      delete 'users/delete_avatar', to: "users/registrations#delete_avatar"
  end

  # Generale Routes
  root to: 'pages#home'
  get '/faq', to:'pages#faq'

  # Contacts
  resources :contacts, only: [:new, :create]

  # Ranking Histories
  resources :ranking_histories, only: [:index, :edit, :update], path: 'ranking-histories' do
    post '/validate',  to:'ranking_histories#validate'
  end

  # Players
  resources :players, only: [:new, :create, :edit, :update] do
    post '/validate', to:'players#validate'
  end

  get '/players', to:'players#index', constraints: lambda { |req| req.format == :json }
  get '/players/:id', to:'players#show', constraints: lambda { |req| req.format == :json }
  get '/players-validations', to:'players#validations'
  get '/stats', to:'players#stats'
  get '/compare', to:'players#compare'

  # Tournaments
  resources :tournaments, only: [:new, :create, :edit, :update] do
    post '/validate', to:'tournaments#validate'
  end

  get '/tournaments', to:'tournaments#index', constraints: lambda { |req| req.format == :json }
  get '/tournaments-validations', to:'tournaments#validations'

  # Games
  resources :games, except: [:show] do
    post '/validate',  to:'games#validate'
  end

end

app/models/ranking_history.rb
class RankingHistory < ApplicationRecord
  # Relations
  belongs_to :ranking
  belongs_to :player

  # Validations
  validates :player, :year, :year_number, presence: true
  validates :player_id, uniqueness: { scope: [:year, :year_number] }

end

app/controllers/ranking_histories_controller.rb
class RankingHistoriesController < ApplicationController
  before_action :set_ranking_history, only: [:edit, :update]

  def index
    @max_date = Game.maximum(:date).year
    @min_date = Game.minimum(:date).year
    @ranking_histories = policy_scope(RankingHistory)
  end

  def edit
    authorize @ranking_history
  end

  def update
    authorize @ranking_history
    if @ranking_history.update(ranking_history_params)
      query = RankingUpdateQuery.new(current_user.player, @ranking_history)
      # Update the ranking of the player in all games played during that ranking period
      query.get_player_games.each do |game_player|
        game_player.update(ranking_id: @ranking_history.ranking.id)
      end

      # Recompute the points of all the opponents faced during that ranking period
      query.get_opponents.each do |player|
        PointsJob.perform_later(player, @ranking_history.end_date)
      end
      
      redirect_to ranking_histories_path
    else
      render :edit
    end
  end
  
  def validate
    @ranking_history = RankingHistory.find(params[:ranking_history_id])
    authorize @ranking_history
    @ranking_history.update(validated: true)

    redirect_back(fallback_location: ranking_histories_path)
  end

  private

  def ranking_history_params
    params.require(:ranking_history).permit(:id, :year, :year_number, :start_date, :end_date, :ranking_id)
  end

  def set_ranking_history
    @ranking_history = RankingHistory.find(params[:id])
  end
end

app/views/ranking_histories/_ranking_history_form.html.erb
<% if edit %>
  <%= f.input :id, as: :hidden %>
<% else %>
  <%= f.input :year, as: :hidden, 
                     input_html: {value: Time.current.year.to_s } %>
  <%= f.input :year_number, as: :hidden,
                            input_html: {value: @year_nbr_dates[:year_number]} %>
  <%= f.input :start_date, as: :hidden,
                           input_html: {value: @year_nbr_dates[:start_date]} %>
  <%= f.input :end_date, as: :hidden,
                         input_html: {value: @year_nbr_dates[:end_date]} %>
  <%= f.input :validated, as: :hidden,
                         input_html: {value: true} %>
<% end %>
<%= f.association :ranking, label: 'Classement', input_html: {data: {target: 'affiliation.ranking'}} %>

app/views/ranking_histories/_ranking_history_form_stand_alone.html.erb
<div class='container'>
  <div class='form-container'>
    <%= simple_form_for(@ranking_history, method: (edit ? 'patch' : 'post')) do |f| %>
      <%= f.input :id, as: :hidden if edit %>
      <%= f.input :year, disabled: true%>
      <%= f.input :start_date, as: :date, html5: true, input_html: {max: '2050-12-31'}, disabled: true%>
      <%= f.input :end_date, as: :date, html5: true, input_html: {max: '2050-12-31'}, disabled: true %>
      <%= f.association :ranking, label: 'Classement' %>
      <div class="form-actions">
        <%= f.button :submit, (edit ? 'Actualiser' : 'Créer'), class:'base-btn' %>
      </div>
    <% end %>
  </div>
</div>

app/views/ranking_histories/_ranking_history_info.html.erb
<h3 class='ranking-title'> Historique de classements </h3>
<table class="ranking-table">
  <tr>
    <th>Année</th>
    <th>Du</th>
    <th>Au</th>
    <th>Classement</th>
    <th>Action</th>
  </tr>
  <% @ranking_histories.each do |year, year_data| %>
    <tr>
      <td> <%= year %> </td>
      <% year_data.each do |ranking| %>
        <td> <%= "#{ranking.start_date.strftime("%d-%m-%Y")}" %> </td>
        <td> <%= "#{ranking.end_date.strftime("%d-%m-%Y")}" %> </td>
        <td> <%= "#{ranking.ranking.name}" %> </td>
        <td>
          <div class="display-flex justify-center align-center">
            <% unless ranking.validated %>
              <a data-method="post" data-remote="true" href="<%= ranking_history_validate_path(ranking) %>" class="fas fa-check tournament-action"></a> | 
            <% end %>
            <a data-method="get" href="<%= edit_ranking_history_path(ranking) %>" class="fas fa-edit tournament-action"></a>
          </div>
       </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/ranking_histories/edit.html.erb
<%= render 'ranking_history_form_stand_alone', edit: true %>

app/views/ranking_histories/index.html.erb
<% content_for :meta_title, "Teqis - Consulte ton historique de classements de tennis" %>
<% content_for :meta_description, "Consulte l'évolution de ton classement au travers des années." %>

<div class='container'>
  <%= render 'ranking_history_info' %>
</div>