config/routes.rb
Rails.application.routes.draw do
  # Rails Admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Blazer
  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "queries"
  end

  # Devise
  devise_for :users, controllers: {registrations: 'users/registrations'}
  devise_scope :user do
      delete 'users/delete_avatar', to: "users/registrations#delete_avatar"
  end

  # Generale Routes
  root to: 'pages#home'
  get '/faq', to:'pages#faq'

  # Contacts
  resources :contacts, only: [:new, :create]

  # Ranking Histories
  resources :ranking_histories, only: [:index, :edit, :update], path: 'ranking-histories' do
    post '/validate',  to:'ranking_histories#validate'
  end

  # Players
  resources :players, only: [:new, :create, :edit, :update] do
    post '/validate', to:'players#validate'
  end

  get '/players', to:'players#index', constraints: lambda { |req| req.format == :json }
  get '/players/:id', to:'players#show', constraints: lambda { |req| req.format == :json }
  get '/players-validations', to:'players#validations'
  get '/stats', to:'players#stats'
  get '/compare', to:'players#compare'

  # Tournaments
  resources :tournaments, only: [:new, :create, :edit, :update] do
    post '/validate', to:'tournaments#validate'
  end

  get '/tournaments', to:'tournaments#index', constraints: lambda { |req| req.format == :json }
  get '/tournaments-validations', to:'tournaments#validations'

  # Games
  resources :games, except: [:show] do
    post '/validate',  to:'games#validate'
  end

end

app/models/game.rb
class Game < ApplicationRecord
  # Relations
  belongs_to :interclub, optional: true
  belongs_to :tournament, optional: true
  belongs_to :court_type, optional: true
  belongs_to :player, optional: true
  belongs_to :round, optional: true
  has_many :game_players, dependent: :destroy
  has_many :players, through: :game_players

  # Nested attributes
  has_many :game_sets, dependent: :destroy
  accepts_nested_attributes_for :game_sets, allow_destroy: true
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_players_and_interclubs_and_clubs_and_courts_and_rounds, only: [:new, :create, :edit, :update]
  before_action :set_game, only: [:edit, :update]

  def index
    @user_player = Player.includes(ranking_histories: :ranking).find(current_user.player.id)
    @player = PlayerDecorator.new(get_player)
    query = PlayerGamesQuery.new(policy_scope(Game), @player)
    respond_to do |format|
      format.html { 
        @max_date = Game.maximum(:date).year
        @min_date = Game.minimum(:date).year
        @tournaments = GameIndexDecorator.new(query.get_tournament_games(@max_date))
        @interclubs = GameIndexDecorator.new(query.get_interclub_games(@max_date))
      }
      format.json { 
        if @player
          tournament_query = GameIndexDecorator.new(params[:year].present? ? query.get_tournament_games(params[:year]) : query.get_tournament_games)
          interclub_query  = GameIndexDecorator.new(params[:year].present? ? query.get_interclub_games(params[:year]) : query.get_interclub_games)
          tournaments = tournament_query.structured_output(@player, current_user, 'tournament')
          interclubs = interclub_query.structured_output(@player, current_user, 'interclub')
        end
        render(json: { html_data: render_to_string(partial: 'games/games_info.html.erb', locals: {player: @player, tournaments: tournaments, interclubs: interclubs })})
       }
    end 
  end

  def new
    @form = GameForm.new
    @form.game_type = "true"
    populate_tournament if session[:tournament_id]
    authorize @form
  end

  def create
    @form = GameForm.new(game_form_params)

    authorize @form
    if @form.save(game_form_params, current_user)
      if params[:create_and_add]
        session[:tournament_id] = @form.tournament_id
        redirect_to new_game_path 
      else
        redirect_to games_path 
      end
    else
      refresh_cascading_dropdowns
      @form.date = @form.date.to_date
      render :new
    end
  end

  def edit
    @form = GameForm.new({}, current_user, @game, true)
    refresh_cascading_dropdowns
    authorize @form
  end

  def update
    @form = GameForm.new(game_form_params, current_user, @game, false)
    authorize @form
    if @form.update(game_form_params, current_user, @game)
      redirect_to games_path
    else
      refresh_cascading_dropdowns
      @form.date = @form.date.to_date
      render :edit
    end 
  end

  def destroy
    @game = Game.includes(:game_players).find(params[:id])
    authorize @game

    user_player_id = current_user.player.id
    game_player = @game.game_players.find{|player| player.player_id == user_player_id}.player
    game_opponent = @game.game_players.find{|player| player.player_id != user_player_id}.player
    game_date = @game.date

    @game.destroy

    PointsJob.perform_later(game_player, game_date)
    PointsJob.perform_later(game_opponent, game_date)

    redirect_to games_path
  end

  def validate
    @game = Game.includes(:game_players).find(params[:game_id])
    authorize @game
    @game.game_players.find{|player| player.player_id == current_user.player.id}.update(validated: true)

    redirect_back(fallback_location: games_path)
  end

  private

  def game_form_params
    params.require(:game_form).permit(:game_type, :interclub_id, :club, :category, :tournament_id, :player_id, :court_type_id, :date, :status, :round_id, :court_type, :indoor, :opponent, :victory, :match_points_saved,
                                      game_sets_attributes: [:id, :set_number, :games_1, :games_2, :_destroy, tie_break_attributes: [:id, :points_1, :points_2, :_destroy]])
  end
  
  def set_players_and_interclubs_and_clubs_and_courts_and_rounds
    @player = PlayerDecorator.new(current_user.player)
    @interclubs = InterclubsMatchingQuery.new(@player).get_interclubs_matching
    @clubs = ClubsMatchingQuery.new(@player).get_clubs_matching
    @courts = CourtType.all.map{|court_type| [court_type.court_type.titleize, court_type.id]}
    @rounds = Round.where.not(name: 'vainqueur').map{|round| [round.name.gsub('_', '/').capitalize, round.id]}
  end

  def set_game
    @game = Game.includes(game_players: {player: {ranking_histories: :ranking}}, game_sets: :tie_break, tournament: [:club, :category]).find(params[:id])
  end

  def populate_tournament
    tournament = Tournament.includes(:club, :category).find(session[:tournament_id])
    session.delete(:tournament_id)
    @form.tournament_id = tournament.id
    @form.club = tournament.club.id
    @form.category = tournament.category_id
    refresh_cascading_dropdowns
  end

  def refresh_cascading_dropdowns
    query = CascadingDropdownsQuery.new(policy_scope(Tournament), @form.club, current_user.player, false)
    @categories = query.select_categories unless @form.club.blank?
    @tournament_dates = query.select_dates(@form.category) unless @form.category.blank?
  end
  
end

app/views/games/_competition_card.html.erb
<div class="tournament-header">
  <% if competition_type == 'tournament' %>
    <div class="display-flex space-between align-center">
      <h4 class="tournament-name"><%= "#{competition[:club]}" %></h4>
      <h4 class="tournament-date"><%= "#{competition[:dates]}" %></h4>
    </div>
    <h6 class="tournament-category"><%= "#{competition[:category]}" %></h6>
  <% else %>
    <h4 class="tournament-name"><%= "#{competition[:division]}" %></h4>
  <% end %>
</div>
  
<table class="tournament-table">
  <tr>
    <th class="th-round"> <%= competition_type == 'tournament' ? 'Tour' : 'Date' %></th>
    <th class="th-victory">V-D</th>
    <th class="th-ranking">Ranking</th>
    <th class="th-opponent">Adversaire</th>
    <th class="th-status">Statut</th>
    <th class="th-score">Score</th>
    <th class="th-actions">Actions</th>
  </tr>
  <% competition[:games].each do |game| %>
    <tr>
      <td><%= competition_type == 'tournament' ? "#{game[:round].capitalize.gsub('_','/')}" : game[:date].strftime("%d-%m-%Y")  %></td>
      <% if game[:victory] %>
        <td>V</td>
      <% else %>
        <td>D</td>
      <% end %>
      <td><%= "#{game[:ranking]}" %></td>
      <td><%= "#{game[:name]}" %></td>
      <% if game[:status] == 'completed' %>
        <td class="tr-status">Terminé</td>
      <% elsif game[:status] == 'WO' %>
        <td class="tr-status">W.O.</td>
      <% elsif game[:status] == 'retirement' %>
        <td class="tr-status">Abandon</td>
      <% end %>
      <td><%="#{game[:score]}" %></td>
      <td>
        <% if competitions.first[:games].first[:player_name] == PlayerDecorator.new(@user_player).player_description ||
          game[:name] == PlayerDecorator.new(@user_player).full_name %>
           <div class="display-flex justify-center align-center"  data-controller='modal'>
            <% unless game[:validated] %>
              <a data-method="post" data-remote="true" href="<%= game_validate_path(game[:game]) %>" class="fas fa-check tournament-action"></a> | 
            <% end %>
            <a data-method="get" href="<%= edit_game_path(game[:game]) %>" class="fas fa-edit tournament-action"></a> |
          
            <div class='terms-modal'  data-target='modal.modal' data-action='click->modal#hide'>
              <div class='terms-modal-content small'>
                <p> Es-tu sûr de vouloir supprimer ce match? </p>
                <div class="display-flex">
                  <a class='modal-link' rel="nofollow" data-method="delete" href="<%= game_path(game[:game]) %>">
                    <div class='modal-btn'>Oui</div>
                  </a>
                  <div class='modal-secondary-btn'>Non</div>
                </div>
              </div>
            </div>
            <i class="fas fa-trash tournament-action" data-action='click->modal#show'></i>
            
          </div>
        <% end %>
      </td> 
    </tr>
  <% end %>
</table>

app/views/games/_game_form.html.erb
<%= simple_form_for(@form, url: (@form.persisted? ? game_path(@form.id) : games_path), 
                           method: (@form.persisted? ? 'patch': 'post'),
                           html: {data: {controller: 'cascading sets autocomplete', action: 'sets#submitForm'}}) do |f| %>

  <%= render 'game_type_toggle'%>
  
  <div class="interclub-block <%= (@form.game_type == "true") ? "visibility-off" : "" %>" data-target='cascading.interclub'>
    <%= f.input :interclub_id, label: 'Division',
                              collection: @interclubs,
                              input_html: {data: {target:'cascading.division'}},
                              disabled: @form.game_type == "true" %>
  </div>

  <div class="tournament-block <%= (@form.game_type == "true") ? "" : "visibility-off" %>" data-target='cascading.tournament'>
    <%= f.input :club, label: 'Club',
                      collection: @clubs, 
                      input_html: {data: {target:'cascading.club', action:'cascading#autofill'}} %>

    <%= f.input :category, label: 'Catégorie', 
                          collection: (@categories.nil? ? [] : @categories), 
                          input_html: {data: {target:'cascading.category', action:'cascading#autofill' }}, 
                          disabled: @form.club.blank? %>

    <%= f.input :tournament_id, label: 'Date du tournoi', 
                                collection: (@tournament_dates.nil? ? [] : @tournament_dates), 
                                input_html: {data: {target:'cascading.date'}}, 
                                disabled: @form.category.blank? %>
  </div>

  <%= f.input :date, label: 'Date du match', as: :date, html5: true, input_html: {max: '2050-12-31'} %>

  <%= f.input :status, label: 'Statut', 
                              collection: [['Terminé','completed'], ['Abandon', 'retirement'],['WO','WO']],
                              input_html: { data: { target:'sets.status', action:'sets#setsHandler' }} %>

  <div class="round-block <%= (@form.game_type == "false") ? "visibility-off" : "" %>" data-target='cascading.round'>       
    <%= f.input :round_id,  label: 'Tour',
                            collection: @rounds,
                            disabled: @form.game_type == "false"%>
  </div>

  <%= f.input :player_id, as: :hidden , 
                          input_html: { value: (@form.player_id.blank? ? current_user.player.id : @form.player_id), name: 'game_form[player_id]'} %>

  <div class='form-flex form-court'>
    <%= f.input :court_type_id, label: 'Terrain',
                                collection: @courts %>
    <%= f.input :indoor, label: 'Indoor?',  as: :boolean %>
  </div>

  <%= f.input :opponent, label: 'Adversaire', 
                         wrapper_html: {class: 'autocomplete', data: {target:'autocomplete.wrapper'}},
                         input_html: {autocomplete:'off', data: {target:'autocomplete.autocomplete', action:'input->autocomplete#autocomplete', 
                                      gender: current_user.player.gender}} %>

  <%= f.input :victory, label: 'Victoire?', as: :boolean %>
  
  <table class='score-table'>
    <tr>
      <th class="th-set-1-1">Set 1</th>
      <th class="th-set-1-2"></th>
      <th class="th-set-2-1">Set 2</th>
      <th class="th-set-2-2"></th>
      <th class="th-set-3-1 visibility-off" data-target='sets.label'>Set 3</th>
      <th class="th-set-3-2"></th>
    </tr>
    <tr>
      <% (1..3).each do |set_number| %>
        <%= render 'set_form_component', f: f, set_number: set_number  %>
      <% end %>
    </tr>
    <tr>
      <% (1..3).each do |set_number| %>
        <%= render 'tie_break_component', f: f, set_number: set_number  %>
      <% end %>
    </tr>
  </table>

  <div class='form-flex score'>
    
  </div>

  <%= f.input :match_points_saved, label: 'Balles de match sauvées',
                                   as: :integer,
                                   input_html: {value: (@form.match_points_saved.blank? ? 0 : @form.match_points_saved)}, 
                                   wrapper_html: {hidden: true, data: {target:'sets.match_points_saved'}} %>

  <div class="form-actions">
    <div class='form-flex justify-center'>
      <% if @form.persisted? %>
        <%= f.button :submit, 'Actualiser', class:'base-btn' %>
      <% else %>
          <%= f.button :submit, 'Ajouter', class:'base-btn' %>
          <%= f.button :submit, 'Ajouter un autre', type: 'submit', name: 'create_and_add', class:'secondary-btn' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/games/_game_type_toggle.html.erb
<div class="form-group">
  <% if @form.game_type == "true" %>
      <input id="game_form_game_type_0" class="toggle toggle-left" name=game_form[game_type] value="true"
              type="radio" data-game-type='tournament' data-target='cascading.tournamentCB' data-action='change->cascading#toggle' checked>
      <label for="game_form_game_type_0" class="toggle-btn">Tournoi</label>
      <input id="game_form_game_type_1" class="toggle toggle-right" name=game_form[game_type] value="false"
              data-game-type='interclub' data-action='change->cascading#toggle' type="radio">
      <label for="game_form_game_type_1" class="toggle-btn">Interclub</label>
  <% else %>
      <input id="game_form_game_type_0" class="toggle toggle-left" name=game_form[game_type] value="true"
              type="radio" data-game-type='tournament' data-target='cascading.tournamentCB' data-action='change->cascading#toggle'>
      <label for="game_form_game_type_0" class="toggle-btn">Tournoi</label>
      <input id="game_form_game_type_1" class="toggle toggle-right" name=game_form[game_type] value="false"
              data-game-type='interclub' data-action='change->cascading#toggle' type="radio" checked>
      <label for="game_form_game_type_1" class="toggle-btn">Interclub</label>
  <% end %>
</div>

app/views/games/_games_info.html.erb
<% if player.present? %>
  <h1 class='page-header'><%= "Résultats - #{player.player_description}" %> </h1>
  <% unless tournaments.blank? %>
    <h3 class='competition-type'> Tournois </h3>
    <% tournaments.each do |tournament| %>
      <div class='tournament'>
        <%= render 'competition_card.html.erb', competitions: tournaments, competition: tournament, competition_type: 'tournament' %>
      </div>
    <% end %>
  <% end %>

  <% unless interclubs.blank? %>
    <h3 class='competition-type'> Interclubs </h3>
    <% interclubs.each do |interclub| %>
      <div class='interclub'>
        <%= render 'competition_card.html.erb', competitions: interclubs, competition: interclub, competition_type: 'interclub' %>
      </div>
    <% end %>
  <% end %>
<% else %>
  <h1 class='page-header'>Joueur non disponible</h1>
<% end %>

app/views/games/_set_form_component.html.erb
<% param_name = "game_form[game_sets_attributes][#{set_number - 1}]" %>

<% if @form.persisted? %>
    <% if @game.game_sets[set_number - 1] %>

        <% attr_name =  "set_#{set_number}_id".to_sym %>
        <%= f.input attr_name, as: :hidden , 
                            input_html: {value: @game.game_sets[set_number - 1].id, name: param_name + '[id]', data: {target: "sets.#{attr_name}"}},
                            wrapper_html: {class: 'visibility-off'} %>

        <% if set_number == 3 %>
            <% attr_name =  "set_#{set_number}_destroy".to_sym %>
            <%= f.input attr_name, as: :hidden , 
                                input_html: { value: false, name: param_name + '[_destroy]', data: {target: "sets.#{attr_name}"}}, 
                                wrapper_html: {class: 'visibility-off'}, disabled: true %>
        <% end %>
    <% end %>
<% end %>


<% attr_name = "set_#{set_number}_number".to_sym %>
<% if set_number != 3 %>
    <%= f.input attr_name, as: :hidden, 
                        input_html: {value: "#{set_number}", name: param_name + '[set_number]', data: {target: "sets.#{attr_name}"}},
                        wrapper_html: {class: 'visibility-off'} %>
<% else %>
    <%= f.input attr_name, as: :hidden,
                        input_html: {value: "#{set_number}", name: param_name + '[set_number]', data: {target: "sets.#{attr_name}"}},
                        wrapper_html: {class: 'visibility-off'},
                        disabled: true %>
<% end %>

<td>
    <% attr_name = "set_#{set_number}_1".to_sym %>
    <% if set_number != 3 %>
        <%= f.input attr_name, label: false, as: :integer,
                               input_html: {name: param_name + "[games_1]", data: {target: "sets.#{attr_name}", action: 'input->sets#setsHandler'}, 
                                            min: 0, max: 7} %>
    <% else %>
        <%= f.input attr_name, label: false, as: :integer,
                            input_html: {name: param_name + "[games_1]", data: {target: "sets.#{attr_name}", action: 'input->sets#setsHandler'},
                                         min: 0, max: 7},
                            wrapper_html: {class: 'visibility-off', data: {target:"sets.#{attr_name}_2"}},
                            disabled: true %>
    <% end %>
</td>
<td>
    <% attr_name =  "set_#{set_number}_2".to_sym %>
    <% if set_number != 3 %>
        <%= f.input attr_name, label: false, as: :integer,
                            input_html: { name: param_name + '[games_2]', data: { target: "sets.#{attr_name}", action: 'input->sets#setsHandler'},
                                          min: 0, max: 7} %>
    <% else %>
        <%= f.input attr_name, label: false, as: :integer,
                            input_html: { name: param_name + '[games_2]', data: { target: "sets.#{attr_name}", action: 'input->sets#setsHandler'},
                                          min: 0, max: 7},
                            wrapper_html: {class: 'visibility-off', data: {target: "sets.#{attr_name}_2"}},
                            disabled: true %>
    <% end %>
</td>

app/views/games/_tie_break_component.html.erb
<% param_name = "game_form[game_sets_attributes][#{set_number - 1}][tie_break_attributes]" %>
<% if @form.persisted? %>
    <% if @game.game_sets[set_number - 1] %>
        <% if @game.game_sets[set_number - 1].tie_break %>

        <% attr_name =  "tie_break_#{set_number}_id".to_sym %>
        <%= f.input attr_name, as: :hidden , 
                            input_html: {value: @game.game_sets[set_number - 1].tie_break.id, name: param_name + '[id]', data: {target: "sets.#{attr_name}"}} %>

        <% attr_name =  "tie_break_#{set_number}_destroy".to_sym %>
        <%= f.input attr_name, as: :hidden , 
                            input_html: {value: false, name: param_name + '[_destroy]', data: {target: "sets.#{attr_name}"}},
                            disabled: true %>
        <% end %>
    <% end %>
<% end %>

<td>
  <% attr_name =  "tie_break_#{set_number}_1".to_sym %>
  <%= f.input attr_name, label: false, as: :integer,
                      input_html: {name: param_name + '[points_1]', data: {target: "sets.#{attr_name}", action: 'input->sets#setsHandler'}}, 
                      wrapper_html: {class: 'visibility-off', data: {target: "sets.#{attr_name}_2"}}, 
                      disabled: true %>


<td>
  <% attr_name =  "tie_break_#{set_number}_2".to_sym %>
  <%= f.input attr_name, label: false, as: :integer,
                        input_html: {name: param_name + '[points_2]', data: {target: "sets.#{attr_name}", action: 'input->sets#setsHandler'}}, 
                        wrapper_html: {class: 'visibility-off', data: {target: "sets.#{attr_name}_2"}},
                        disabled: true %>
</td>

app/views/games/_tournament_card.html.erb
<div class="tournament-header">
  <div class="display-flex space-between align-center">
    <h4 class="tournament-name"><%= "#{tournament[:club]}" %></h4>
    <h4 class="tournament-date"><%= "#{tournament[:dates]}" %></h4>
  </div>
  <h6 class="tournament-category"><%= "#{tournament[:category]}" %></h6>
</div>
<table class="tournament-table">
  <tr>
    <th class="th-round">Tour</th>
    <th class="th-ranking">Classement</th>
    <th class="th-opponent">Adversaire</th>
    <th class="th-victory">V-D</th>
    <th class="th-status">Status</th>
    <th class="th-score">Score</th>
    <th class="th-actions">Actions</th>
  </tr>
  <% tournament[:games].each do |game| %>
    <tr>
      <td><%= "#{game[:round].capitalize.gsub('_','/')}" %></td>
      <td><%= "#{game[:ranking]}" %></td>
      <td><%= "#{game[:name]}" %></td>
      <% if game[:victory] %>
        <td>V</td>
      <% else %>
        <td>D</td>
      <% end %>
      <% if game[:status] == 'completed' %>
        <td>Terminé</td>
      <% elsif game[:status] == 'WO' %>
        <td>W.O.</td>
      <% elsif game[:status] == 'retirement' %>
        <td>Blessure</td>
      <% end %>
      <td><%="#{game[:score]}" %></td>
      <td>
        <% if structured_output.first[:games].first[:player_name] == PlayerDecorator.new(@user_player).player_description ||
          game[:name] == PlayerDecorator.new(@user_player).full_name %>
           <div class="display-flex justify-center align-center">
            <% unless game[:validated] %>
              <a data-method="post" data-remote="true" href="<%= game_validate_path(game[:game]) %>" class="fas fa-check tournament-action"></a> | 
            <% end %>
            <a data-method="get" href="<%= edit_game_path(game[:game]) %>" class="fas fa-edit tournament-action"></a> |
            <a rel="nofollow" data-method="delete" href="<%= game_path(game[:game]) %>" class="fas fa-trash tournament-action"></a>
          </div>
        <% end %>
      </td> 
    </tr>
  <% end %>
</table>

app/views/games/edit.html.erb
<div class='container'>
  <div class='form-container'>
    <%= render 'game_form' %>
  </div>
</div>

app/views/games/index.html.erb
<% content_for :meta_title, 'Teqis - Consulte tes résultats de tennis' %>
<% content_for :meta_description, "Consulte tes résultats de tournois et d'interclubs de la saison en cours ou de n'importe quelle autre saison." %>

<div class='container' data-controller='filter autocomplete'>
  <%= render 'shared/year_and_player_search', max_date: @max_date, min_date: @min_date, search_type: 'games' %>
  <div data-target='filter.container'>
      <%= render 'games_info', player: @player, tournaments: @tournaments.structured_output(@user_player, current_user, 'tournament'), 
                                                interclubs: @interclubs.structured_output(@user_player, current_user, 'interclub') %>
  </div>
</div>

app/views/games/new.html.erb
<% content_for :meta_title, "Teqis - Enregistre tes résultats de tennis" %>
<% content_for :meta_description, "Enregistre en quelques secondes tes résultats de tournois ou d'interclubs" %>

<div class='container'>
  <div class='form-container'>
    <%= render 'game_form' %>
  </div>
</div>