config/routes.rb
Rails.application.routes.draw do
  # Rails Admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Blazer
  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "queries"
  end

  # Devise
  devise_for :users, controllers: {registrations: 'users/registrations'}
  devise_scope :user do
      delete 'users/delete_avatar', to: "users/registrations#delete_avatar"
  end

  # Generale Routes
  root to: 'pages#home'
  get '/faq', to:'pages#faq'

  # Contacts
  resources :contacts, only: [:new, :create]

  # Ranking Histories
  resources :ranking_histories, only: [:index, :edit, :update], path: 'ranking-histories' do
    post '/validate',  to:'ranking_histories#validate'
  end

  # Players
  resources :players, only: [:new, :create, :edit, :update] do
    post '/validate', to:'players#validate'
  end

  get '/players', to:'players#index', constraints: lambda { |req| req.format == :json }
  get '/players/:id', to:'players#show', constraints: lambda { |req| req.format == :json }
  get '/players-validations', to:'players#validations'
  get '/stats', to:'players#stats'
  get '/compare', to:'players#compare'

  # Tournaments
  resources :tournaments, only: [:new, :create, :edit, :update] do
    post '/validate', to:'tournaments#validate'
  end

  get '/tournaments', to:'tournaments#index', constraints: lambda { |req| req.format == :json }
  get '/tournaments-validations', to:'tournaments#validations'

  # Games
  resources :games, except: [:show] do
    post '/validate',  to:'games#validate'
  end

end

app/models/player.rb
class Player < ApplicationRecord
  # Relations
  belongs_to :user, optional: true
  belongs_to :club
  has_many :game_players
  has_many :games, through: :game_players
  has_many :tournaments, through: :games
  has_many :categories, through: :tournaments
  has_many :ranking_histories, dependent: :destroy
  has_many :ranking, through: :ranking_histories

  # Reflexive Relation
  belongs_to :player_creator, class_name: 'Player', optional: true, foreign_key: 'player_creator_id'
  has_many :players_created, class_name: 'Player', foreign_key: 'player_creator_id'

  # Nested attributes
  accepts_nested_attributes_for :ranking_histories

  # Validations
  validates :affiliation_number, :gender, :first_name, :last_name, :dominant_hand, presence: true
  validates :birthdate, presence: true, unless: :user_added?
  validates :affiliation_number, format: { with: /\A\d{7}\z/, message: "le numéro d'affiliation doit être composé de 7 chiffres"}, allow_blank: true
  validate :affiliation_number_check, on: :create
  
  # PG Search
  include PgSearch::Model
  pg_search_scope :search_by_name_and_affiliation_number,
    against: [:first_name, :last_name, :affiliation_number],
    using: {
      tsearch: { prefix: true }
  }
  
  private 

  # Custom Validations
  def affiliation_number_check
    player = Player.find_by_affiliation_number(self.affiliation_number)
    # Created through nested attributes
    if self.user
      if player
          errors.add(:affiliation_number, 'Déjà associé à un autre e-mail') if (!player.user_id.nil? && (player.user.email != self.user.email))
      end
    # Create as a stand-alone player
    else
      errors.add(:affiliation_number, 'Déjà existant') if (player && self.new_record?)
    end
  end
  
  def user_added?
    !self.player_creator_id.nil?
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_player, only: [:edit, :update]
  before_action :set_player_ajax, only: [:show]

  def index
    if params[:search].present?
      if params[:gender].present?
        @players = policy_scope(Player).includes(ranking_histories: :ranking).search_by_name_and_affiliation_number(params[:search])
                                       .select{|player| player.gender == params[:gender]}.first(10)
      else  
        @players = policy_scope(Player).includes(ranking_histories: :ranking).search_by_name_and_affiliation_number(params[:search]).first(10)
      end
    else
      @players = policy_scope(Player).includes(ranking_histories: :ranking).first(10)
    end
    @players = @players.map{|player| PlayerDecorator.new(player)}
    render json: { error: "Couldn't find #{params[:query].titleize}"} , status: :not_found if (@players.size == 0)
  end

  def show
    authorize @player
  end
  
  def new
    @player = Player.new
    @player.ranking_histories.build
    @year_nbr_dates = YearDatesService.get_year_nbr_dates
    authorize @player
  end

  def create
    @player = Player.new(player_params)    
    @player.player_creator_id  = current_user.player.id
    @player.validated = (current_user.admin ? current_user.admin : false)
    @year_nbr_dates = YearDatesService.get_year_nbr_dates

    authorize @player
    if @player.save
      redirect_to games_path
    else
      render :new
    end
  end

  def edit
    authorize @player
  end

  def update
    authorize @player
    if @player.update(player_params)
      redirect_to games_path
    else
      render :edit
    end
  end

  def stats
    @player = get_player
    @user_player = Player.includes(ranking_histories: :ranking).find(current_user.player.id)
    authorize @user_player
    @query = PlayersQuery.new(@player)

    respond_to do |format|
      format.html { 
        @max_date = Game.maximum(:date).year
        @min_date = Game.minimum(:date).year
        @year = @max_date
      }
      format.json { 
        @year = (params[:year].present? ? params[:year] : nil)
        render(json: { html_data: render_to_string(partial: 'players/stats_info.html.erb')})
       }
    end 
  end

  def compare
    @user_player = Player.includes(ranking_histories: :ranking).find(current_user.player.id)
    @player = get_player
    authorize @user_player
    @query_user_player = PlayersQuery.new(@user_player)
    @query_player = PlayersQuery.new(@player)
    respond_to do |format|
      format.html { 
        @max_date = Game.maximum(:date).year
        @min_date = Game.minimum(:date).year
        @year = @max_date
      }
      format.json { 
        @year = (params[:year].present? ? params[:year] : nil)
        render(json: { html_data: render_to_string(partial: 'players/compare_info.html.erb')})
       }
    end 

  end

  def validations
    @players = policy_scope(Player).includes(:club, ranking_histories: :ranking).where(players: {validated: false})
    authorize @players
  end

  def validate
    @player = Player.find(params[:player_id])
    authorize @player
    @player.update(validated: true)

    redirect_back(fallback_location: players_validations_path)
  end

  private

  def player_params
    params.require(:player).permit(:id, :affiliation_number, :first_name, :last_name, :club_id, :birthdate, :gender, :dominant_hand,
                                   ranking_histories_attributes: [:id, :ranking_id, :year, :year_number, :start_date, :validated, :end_date])
  end

  def set_player
    @player = Player.find(params[:id])
  end

  def set_player_ajax
    @player = Player.find_by_affiliation_number!(params[:id])
  end
end
  

app/views/players/_compare_category.html.erb
<% if user.key?(true) %>
  <ul class='compare-element display-flex space-between'>
    <li class='stat <%= (user[true] == player[true] ? 'equal' : (user[true] > player[true] ? 'positive' : 'negative')) %>'>
      <% if user[true] != 0 || user[false] != 0 %>
        <%= "#{user[true]} (#{number_to_percentage((user[true] / (user[true]+user[false]).to_f)*100, precision: 0)})" %>
      <% else %>
        <%= "#{user[true]} (#{number_to_percentage(0, precision: 0)})" %>
      <% end %>
    </li>
    <li>Victoires</li>
    <li class='stat <%= (user[true] == player[true] ? 'equal' : (user[true] < player[true] ? 'positive' : 'negative')) %>'>
      <% if player[true] != 0 || player[false] != 0 %>
        <%= "#{player[true]} (#{number_to_percentage((player[true] / (player[true]+player[false]).to_f)*100, precision: 0)})" %>
      <% else %>
        <%= "#{player[true]} (#{number_to_percentage(0, precision: 0)})" %>
      <% end %>
    </li>
  </ul>
<% else %>
  <% user.each do |k, v| %>
      <% if player[k] %>
        <ul class='compare-element display-flex space-between'>
          <li class='stat <%= (v[true] == player[k][true] ? 'equal' : (v[true] > player[k][true] ? 'positive' : 'negative')) %>'>
            <%= "#{v[true]} (#{number_to_percentage((v[true] / (v[true]+v[false]).to_f)*100, precision: 0)})" %>
          </li>
          <li><%= "#{k}" %></li>
          <li class='stat <%= (v[true] == player[k][true] ? 'equal' : (v[true] < player[k][true] ? 'positive' : 'negative')) %>'>
            <%= "#{player[k][true]} (#{number_to_percentage((player[k][true] / (player[k][true]+player[k][false]).to_f)*100, precision: 0)})" %>
          </li>
        </ul>
      <% end %>
  <% end %>
<% end %>

app/views/players/_compare_info.html.erb
<% if @user_player.present? && @player.present? && (@user_player != @player) %>
  <h1 class='page-header'>Comparaisons</h1>
   <div data-controller='canvas'>
     <%= render 'compare_header.html.erb' %>
     <div class='compare-block'>
       <%= render 'compare_category.html.erb', user: @query_user_player.get_nbr_wins_losses(nil, @year),
                                               player: @query_player.get_nbr_wins_losses(nil, @year) %>
     </div>
     
     <div class='compare-block'>
       <h3 class="compare-category-title"> Par Classement </h3>
       <%= render 'compare_category.html.erb', user: @query_user_player.get_wins_by_ranking(nil, @year),
                                               player: @query_player.get_wins_by_ranking(nil, @year) %>
     </div>
     <div class='compare-block'>
       <h3 class="compare-category-title"> Autres Stats </h3>
       <%= render 'compare_category.html.erb', user: @query_user_player.get_wins_losses_nbr_sets(nil, nil, @year),
                                               player: @query_player.get_wins_losses_nbr_sets(nil, nil, @year) %>
       <%= render 'compare_category.html.erb', user:  @query_user_player.get_wins_losses_by('tournament', nil, @year),
                                               player: @query_player.get_wins_losses_by('tournament', nil, @year) %>
       <%= render 'compare_category.html.erb', user:  @query_user_player.get_wins_losses_by('dominant_hand', nil, @year),
                                               player: @query_player.get_wins_losses_by('dominant_hand', nil, @year) %>
       <%= render 'compare_category.html.erb', user:  @query_user_player.get_wins_losses_by('indoor', nil, @year),
                                               player: @query_player.get_wins_losses_by('indoor', nil, @year) %>
       <%= render 'compare_category.html.erb', user:  @query_user_player.get_wins_losses_by('court_type', nil, @year),
                                               player: @query_player.get_wins_losses_by('court_type', nil, @year) %>
       <%= render 'compare_category.html.erb', user:  @query_user_player.get_wins_losses_tie_breaks(nil, @year),
                                               player: @query_player.get_wins_losses_tie_breaks(nil, @year) %>
     </div>
   </div>
<% else %>
  <h1 class='page-header'>Veuillez sélectionner un joueur contre lequel vous comparer.</h1>
<% end %>

app/views/players/_player_form.html.erb
<%= f.input :id, as: :hidden if edit %>

<% if autofill %>
  <%= f.input :affiliation_number, label: "Numéro d'affiliation", 
                                   input_html: {data: {target: 'affiliation.number', action: 'affiliation#autofill'}} %>
<% else %>
  <%= f.input :affiliation_number, label: "Numéro d'affiliation", 
                                   input_html: {data: {target: 'affiliation.number'}} %>
<% end %>
<%= f.input :first_name, label: 'Prénom', 
                         input_html: {data: {target: 'affiliation.firstName'}} %>
<%= f.input :last_name, label: 'Nom', 
                        input_html: {data: {target: 'affiliation.lastName'}} %>
<%= f.association :club, label: 'Club',
                         input_html: {data: {target: 'affiliation.club'}} %>
<%= f.input :birthdate, label: "Date de naissance", as: :date, html5: true, input_html: {max: '2050-12-31'} %>
<%= f.input :gender, label: 'Sexe', 
                     collection:[['Homme', 'male'], ['Femme', 'female']], 
                     input_html: {data: {target: 'affiliation.gender'}} %>
<%= f.input :dominant_hand, label: 'Main dominante', 
                            collection: [['Droitier', 'right-handed'], ['Gaucher', 'left-handed']], 
                            input_html: {data: {target:'affiliation.dominantHand'}} %>

app/views/players/_players_validations.html.erb
<h3 class='validation-title'> Joueurs </h3>
<table class="validation-table">
  <tr>
    <th>Club</th>
    <th>Nº Affiliation</th>
    <th>Sexe</th>
    <th>Classement</th>
    <th>Prénom</th>
    <th>Nom</th>
    <th>Main Dominante</th>
    <th>Anniversaire</th>
    <th>Action</th>
  </tr>
  <% @players.each do |player| %>
    <tr>
      <td> <%= player.club.name %> </td>
      <td> <%= player.affiliation_number %> </td>
      <td> <%= player.gender == 'male' ? 'Homme' : 'Femme' %> </td>
      <td> <%= "#{player.ranking_histories.max_by{|ranking| ranking.start_date}.ranking.name}" %> </td>
      <td> <%= player.first_name %> </td>
      <td> <%= player.last_name %> </td>
      <td> <%= player.dominant_hand == 'left-handed' ? 'Gaucher' : 'Droitier' %> </td>
      <td> <%= player.birthdate.strftime("%d-%m-%Y") %> </td>
      <td>
        <div class="display-flex justify-center align-center">
          <a data-method="post" data-remote="true" href="<%= player_validate_path(player) %>" class="fas fa-check tournament-action"></a> | 
          <a data-method="get" href="<%= edit_player_path(player) %>" class="fas fa-edit tournament-action"></a>
        </div>
      </td>
    </tr>
  <% end %>
</table>

app/views/players/_stats_avatar.html.erb
<% if player.user %>
  <% if player.user.avatar.attached? %>
    <%= cl_image_tag(player.user.avatar.key, class: "#{stats ? 'stats-avatar-img-round' : 'compare-avatar-img-round'}") %>
  <% else %>
    <%= image_tag("#{player.gender == 'male' ? 'stats/boy.png' : 'stats/girl.png'}", 
                      class: "#{stats ? 'stats-avatar-img' : 'compare-avatar-img'}") %>
  <% end %>
<% else %>
  <%= image_tag("#{player.gender == 'male' ? 'stats/boy.png' : 'stats/girl.png'}", 
                   class: "#{stats ? 'stats-avatar-img' : 'compare-avatar-img'}") %>
<% end %>

app/views/players/_stats_category.html.erb
<% if query_data.present? %>
  <div class='stats-block'>
    <h3 class="stats-category-title"> <%= title %> </h3>
    <div class="container">
        <div class="row">
        <% query_data.each do |k, v|%>
          <% unless k.nil? %>
            <div class="col-12 col-lg-6">
                <div class="stats-category display-flex">
                <div class="stats-category-description">
                    <%= image_tag(img_url, class: 'stats-category-img') %>
                    <h5 class="stats-category-name"><%= k %></h5>
                </div>
                <%= render 'stats_wins_losses.html.erb', wins: v[true], losses: v[false], head_to_head: false, header: false %>
                </div>
            </div>
          <% end %>
        <% end %>
        </div>
    </div>
  </div>
<% end %>

app/views/players/_stats_header.html.erb
<div class='stats-block first-block'>
  <div class="stats-header display-flex space-between">
    <div class="display-flex align-center stats-avatar-img-div">
      <%= render 'stats_avatar.html.erb', player: @player, stats: true %>
    </div>
    <%= render 'stats_wins_losses.html.erb', wins: @query.get_nbr_wins_losses(true,  @year),
                                             losses: @query.get_nbr_wins_losses(false,  @year),
                                             head_to_head: false,
                                             header: true %>
  </div>
</div>

app/views/players/_stats_match_points.html.erb
<% if !saved.zero? || !missed.zero? %>
  <div class='stats-block'>
    <h3 class="stats-category-title"> <%= title %> </h3>
    <div class="container">
      <% if !saved.zero? %>
        <div class="row">
          <div class="col-12 col-lg-6">
              <div class="stats-category display-flex">
                <div class="stats-category-description">
                    <%= image_tag(img_url, class: 'stats-category-img') %>
                    <h5 class="stats-category-name">Sauvées</h5>
                </div>
                <div class="stats-category-saved-container">
                  <div class="stats-category-saved"><%= saved %></div>
                </div>
              </div>
          </div>
        </div>
      <% end %>
      <% if !missed.zero? %>
        <div class="row">
          <div class="col-12 col-lg-6">
              <div class="stats-category display-flex">
                <div class="stats-category-description">
                    <%= image_tag(img_url, class: 'stats-category-img') %>
                    <h5 class="stats-category-name">Ratées</h5>
                </div>
                <div class="stats-category-saved-container">
                  <div class="stats-category-missed"><%= -missed %></div>
                </div>
              </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/players/_stats_rankings.html.erb
<% if query_data.present? %>
  <div class='stats-block'>
    <h3 class="stats-category-title"> Par Classement </h3>
    <div class='stats-ranking-mobile'>
      <% query_data.each do |k, v| %>
        <ul data-target='canvas.barChartData' class='stats-ranking-mobile-card display-flex space-between <%= ((v[true] == v[false]) ? 'equal' : (v[true] > v[false]) ? 'positive' : 'negative') %>'>
          <li><%= "#{k}" %></li>
          <li><%= "V: #{v[true]} (#{number_to_percentage((v[true] / (v[true]+v[false]).to_f)*100, precision: 0)})" %></li>
          <li><%= "D: #{v[false]} (#{number_to_percentage((v[false] / (v[true]+v[false]).to_f)*100, precision: 0)})" %></li>
        </ul>
      <% end %>
    </div>

    <div class='stats-ranking-desktop'>
      <canvas id='stats-ranking-bar-chart' data-target='canvas.barChart' ></canvas>
    </div>
  </div>
<% end %>

app/views/players/_stats_tournaments.html.erb
<% if tournaments.present? %>
  <div class='stats-block'>
    <h3 class="stats-category-title"> <%= title %> </h3>
    <div class="container">
      <div class="row">
        <div class="col-12">
            <div class="stats-category-tournament display-flex">
              <div class="stats-category-description">
                  <%= image_tag(img_url, class: 'stats-category-img') %>
                  <h5 class="stats-category-name">Gagnés</h5>
              </div>
              <div class="stats-category-tournament-details">
                <ul>
                  <% tournaments.each do |tournament| %>
                    <li> <%= "#{tournament.tournament.start_date.strftime("%d-%m-%Y")} / #{tournament.tournament.end_date.strftime("%d-%m-%Y")} -  
                              #{tournament.tournament.club.name.titleize} - #{tournament.tournament.category.category}" %> </li>
                  <% end %>
                </ul>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/players/_stats_wins_losses.html.erb
<% if wins.present? && losses.present? %>
  <div class='wins-losses-div <%= header ? 'header' : 'category' %>'>
    <% unless wins.zero? && losses.zero? %>
      <% unless head_to_head %>
        <h5 class='wins-losses-title'>VICTOIRES - <em> DÉFAITES </em> </h5>
      <% end %>
      
      <div class='display-flex justify-center align-center'>
        <div class='wins-losses-numbers-div'>
          <h2 class='wins-number'><%= wins %></h2>
          <h5 class='wins-percentage'><%= number_to_percentage((wins / (wins+losses).to_f)*100, precision: 0) %></h5>
        </div>
        <% if header %>
          <canvas id='stats-header-donut-chart' data-target='canvas.winsLosses'> </canvas>
        <% else %>
          <canvas class='stats-category-donut-chart' data-target='canvas.winsLosses'> </canvas>
        <% end %>
        <div class='wins-losses-numbers-div'>
          <h2 class='losses-number'><%= losses %></h2>
          <h5 class='losses-percentage'><%= number_to_percentage((losses / (wins+losses).to_f)*100, precision: 0) %></h5>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/players/compare.html.erb
<% content_for :meta_title, "Teqis - Compare tes résultats de tennis aux autres joueurs et joueuses de ta région" %>
<% content_for :meta_description, "Compare toi facilement aux autres joueurs et joueuses de ta région à travers des statistiques intéressantes. 
                                   Tu peux spécifier une saison spécifique ou encore comparer l'entièreté de l'historique de résultats." %>

<div class='container' data-controller='filter autocomplete'>
  <%= render 'shared/year_and_player_search', max_date: @max_date, min_date: @min_date, search_type: 'compare' %>
  <div data-target='filter.container'>
    <%= render 'compare_info.html.erb' %>
  </div>
</div>

app/views/players/new.html.erb
<% content_for :meta_title, "Teqis - Rajoute un joueur de tennis" %>
<% content_for :meta_description, "Rajoute en quelques secondes un nouveau joueur." %>

<div class='container'>
  <div class='form-container'>
    <%= simple_form_for(@player, method: 'post') do |f| %>
      <%= render 'player_form', f: f, autofill: false, edit: false %>
      <%= f.simple_fields_for :ranking_histories do |rh| %>
        <%= render 'ranking_histories/ranking_history_form', f: rh,  edit: false %>
      <% end %>
      <div class="form-actions">
        <%= f.button :submit, 'Créer', class:'base-btn' %>
      </div>
    <% end %>
  </div>
</div>

app/views/players/stats.html.erb
<% content_for :meta_title, 'Teqis - Analyse tes statistiques de tennis' %>
<% content_for :meta_description, "Analyse en détail tes statistiques pour la saison en cours comme pour n'importe quelle autre saison ou encore l'entièreté de ton historique de matchs." %>

<div class='container' data-controller='filter autocomplete'>
  <%= render 'shared/year_and_player_search', max_date: @max_date, min_date: @min_date, search_type: 'stats' %>
  <div data-target='filter.container'>
    <%= render 'stats_info' %>
  </div>
</div>